# Milestone 3
Cleaning/Formatting Website Data

Perform at least 5 data transformation and/or cleansing steps to your website data. For example:

Replace Headers
Format data into a more readable format
Identify outliers and bad data
Find duplicates
Fix casing or inconsistent values
Conduct Fuzzy Matching
You can submit a Jupyter Notebook or a PDF of your code. If you submit a .py file you need to also include a PDF or attachment of your results.

In [7]:
# User python 3 as runtime environment
#Import the pandas library
import pandas as pd

In [8]:
# Load the data from 
# df = pd.read_html("https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html#states")
df = pd.read_html("https://en.wikipedia.org/wiki/Statistics_of_the_COVID-19_pandemic_in_the_United_States")
len(df)

37

In [9]:
# Loop throught the dataframe formed and print the shape of each dataframe
for t in df:
    print(t.shape)

(58, 10)
(12, 4)
(1, 2)
(1, 2)
(105, 3)
(44, 2)
(1, 2)
(2, 2)
(1, 2)
(8, 2)
(7, 2)
(4, 2)
(3, 2)
(3, 2)
(2, 2)
(8, 2)
(7, 2)
(2, 2)
(2, 2)
(1, 2)
(16, 2)
(3, 2)
(3, 2)
(1, 2)
(2, 2)
(3, 2)
(23, 2)
(2, 2)
(1, 2)
(9, 2)
(8, 2)
(6, 2)
(1, 2)
(4, 2)
(3, 2)
(9, 3)
(7, 2)

In [10]:
# Print the first dataframe thats what we need for further analysis
df[0]

   [show all].mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vteCOVID-19 pandemic in the United States by state and territory  \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        U.S. state or territory[i]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           56 / 56
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN
26                                                NaN
27                                                NaN
28                                                NaN
29                                                NaN
30                                                NaN
31                                                NaN
32                                                NaN
33                                                NaN
34                                                NaN
35                                                NaN
36                                                NaN
37                                                NaN
38                                                NaN
39                                                NaN
40                                                NaN
41                                                NaN
42                                                NaN
43                                                NaN
44                                                NaN
45                                                NaN
46                                                NaN
47                                                NaN
48                                                NaN
49                                                NaN
50                                                NaN
51                                                NaN
52                                                NaN
53                                                NaN
54                                                NaN
55                                                NaN
56  Most recent edit: 21:14, Thursday, January 14,...
57  ^ Nationality and location of original infecti...

                                                       \

                                            56 / 56.1
0                                             Alabama
1                                              Alaska
2                                      American Samoa
3                                             Arizona
4                                            Arkansas
5                                          California
6                                            Colorado
7                                         Connecticut
8                                            Delaware
9                                District of Columbia
10                                       Florida[vii]
11                                            Georgia
12                                               Guam
13                                             Hawaii
14                                              Idaho
15                                           Illinois
16                                            Indiana
17                                               Iowa
18                                             Kansas
19                                           Kentucky
20                                          Louisiana
21                                              Maine
22                                           Maryland
23                                      Massachusetts
24                                           Michigan
25                                          Minnesota
26                                        Mississippi
27                                           Missouri
28                                            Montana
29                                           Nebraska
30                                             Nevada
31                                      New Hampshire
32                                         New Jersey
33                                         New Mexico
34                                           New York
35                                     North Carolina
36                                       North Dakota
37                           Northern Mariana Islands
38                                               Ohio
39                                           Oklahoma
40                                             Oregon
41                                       Pennsylvania
42                                        Puerto Rico
43                                       Rhode Island
44                                     South Carolina
45                                       South Dakota
46                                          Tennessee
47                                              Texas
48                                  US Virgin Islands
49                                               Utah
50                                            Vermont
51                                           Virginia
52                                         Washington
53                                      West Virginia
54                                          Wisconsin
55                                            Wyoming
56  Most recent edit: 21:14, Thursday, January 14,...
57  ^ Nationality and location of original infecti...

                                                       \
                                            Cases[ii]
                                        21,529,667[v]
0                                              374095
1                                               46552
2                                                   3
3                                              618546
4                                              233475
5                                             2747288
6                                              337161
7                                              185708
8                                               56596
9                                               29252
10                                            1503482
11                                             575395
12                                               7399
13                                              25470
14                                             141077
15                                            1046030
16                                             563653
17                                             282439
18                                             229079
19                                             265262
20                                             315275
21                                              29611
22                                             283171
23                                             375178
24                                             562553
25                                             437552
26                                             218386
27                                             397299
28                                              81555
29                                             162849
30                                             220124
31                                              42697
32                                             590162
33                                             139875
34                                            1155370
35                                             629124
36                                              90948
37                                                122
38                                             792938
39                                             269276
40                                             105970
41                                             741389
42                                             109747
43                                              82066
44                                             282230
45                                              91038
46                                             653869
47                                            1995292
48                                               2143
49                                             258697
50                                               8619
51                                             323915
52                                             221695
53                                              77239
54                                             506890
55                                              43704
56  Most recent edit: 21:14, Thursday, January 14,...
57  ^ Nationality and location of original infecti...

                                                       \
                                               Deaths
                                           350,816[v]
0                                                4878
1                                                 214
2                                                   0
3                                               10141
4                                                3749
5                                               30513
6                                           4,873[vi]
7                                                5995
8                                                 921
9                                                 788
10                                              23585
11                                               9889
12                                                124
13                                                285
14                                               1436
15                                              17840
16                                               8613
17                                               3898
18                                               2879
19                                               2623
20                                               7488
21                                                438
22                                               5799
23                                              12423
24                                              14145
25                                               5711
26                                               4816
27                                               5540
28                                                961
29                                               1587
30                                               3019
31                                                735
32                                              19932
33                                               2403
34                                       32,007[viii]
35                                               7578
36                                               1152
37                                                  2
38                                               9802
39                                               2064
40                                               1138
41                                              18429
42                                               1272
43                                               1509
44                                               4739
45                                               1259
46                                               7785
47                                              30219
48                                                 24
49                                               1055
50                                                155
51                                               4411
52                                               2879
53                                                968
54                                               5157
55                                                405
56  Most recent edit: 21:14, Thursday, January 14,...
57  ^ Nationality and location of original infecti...

                                                       \
                                          Recov.[iii]
                                                    –
0                                              202137
1                                                7165
2                                                   –
3                                                   –
4                                              205462
5                                                   –
6                                                   –
7                                                   –
8                                               18371
9                                               17745
10                                                  –
11                                                  –
12                                               6660
13                                              11385
14                                              46247
15                                                  –
16                                             367800
17                                             188922
18                                                  –
19                                              36740
20                                             217930
21                                              10491
22                                                  –
23                                             187221
24                                             415079
25                                             417005
26                                             136627
27                                                  –
28                                              62778
29                                              80829
30                                                  –
31                                              23046
32                                                  –
33                                              43091
34                                             111141
35                                             521475
36                                              82935
37                                                 29
38                                             648724
39                                             200512
40                                                  –
41                                             556042
42                                                  –
43                                                  –
44                                                  –
45                                              77032
46                                             565197
47                                      1,595,600[ix]
48                                               1984
49                                             176211
50                                               5657
51                                                  –
52                                                  –
53                                              42462
54                                             472862
55                                              35281
56  Most recent edit: 21:14, Thursday, January 14,...
57  ^ Nationality and location of original infecti...

                                                       \
                                            Hosp.[iv]
                                                    –
0                                               34373
1                                                1013
2                                                   –
3                                               43582
4                                               11514
5                                                   –
6                                               16092
7                                               12257
8                                                   –
9                                                   –

In [11]:
# Print the shape of first dataframe
df[0].shape

(58, 10)

In [12]:
scraped_df = df[0]
scraped_df

   [show all].mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vteCOVID-19 pandemic in the United States by state and territory  \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        U.S. state or territory[i]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           56 / 56
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN
26                                                NaN
27                                                NaN
28                                                NaN
29                                                NaN
30                                                NaN
31                                                NaN
32                                                NaN
33                                                NaN
34                                                NaN
35                                                NaN
36                                                NaN
37                                                NaN
38                                                NaN
39                                                NaN
40                                                NaN
41                                                NaN
42                                                NaN
43                                                NaN
44                                                NaN
45                                                NaN
46                                                NaN
47                                                NaN
48                                                NaN
49                                                NaN
50                                                NaN
51                                                NaN
52                                                NaN
53                                                NaN
54                                                NaN
55                                                NaN
56  Most recent edit: 21:14, Thursday, January 14,...
57  ^ Nationality and location of original infecti...

                                                       \

                                            56 / 56.1
0                                             Alabama
1                                              Alaska
2                                      American Samoa
3                                             Arizona
4                                            Arkansas
5                                          California
6                                            Colorado
7                                         Connecticut
8                                            Delaware
9                                District of Columbia
10                                       Florida[vii]
11                                            Georgia
12                                               Guam
13                                             Hawaii
14                                              Idaho
15                                           Illinois
16                                            Indiana
17                                               Iowa
18                                             Kansas
19                                           Kentucky
20                                          Louisiana
21                                              Maine
22                                           Maryland
23                                      Massachusetts
24                                           Michigan
25                                          Minnesota
26                                        Mississippi
27                                           Missouri
28                                            Montana
29                                           Nebraska
30                                             Nevada
31                                      New Hampshire
32                                         New Jersey
33                                         New Mexico
34                                           New York
35                                     North Carolina
36                                       North Dakota
37                           Northern Mariana Islands
38                                               Ohio
39                                           Oklahoma
40                                             Oregon
41                                       Pennsylvania
42                                        Puerto Rico
43                                       Rhode Island
44                                     South Carolina
45                                       South Dakota
46                                          Tennessee
47                                              Texas
48                                  US Virgin Islands
49                                               Utah
50                                            Vermont
51                                           Virginia
52                                         Washington
53                                      West Virginia
54                                          Wisconsin
55                                            Wyoming
56  Most recent edit: 21:14, Thursday, January 14,...
57  ^ Nationality and location of original infecti...

                                                       \
                                            Cases[ii]
                                        21,529,667[v]
0                                              374095
1                                               46552
2                                                   3
3                                              618546
4                                              233475
5                                             2747288
6                                              337161
7                                              185708
8                                               56596
9                                               29252
10                                            1503482
11                                             575395
12                                               7399
13                                              25470
14                                             141077
15                                            1046030
16                                             563653
17                                             282439
18                                             229079
19                                             265262
20                                             315275
21                                              29611
22                                             283171
23                                             375178
24                                             562553
25                                             437552
26                                             218386
27                                             397299
28                                              81555
29                                             162849
30                                             220124
31                                              42697
32                                             590162
33                                             139875
34                                            1155370
35                                             629124
36                                              90948
37                                                122
38                                             792938
39                                             269276
40                                             105970
41                                             741389
42                                             109747
43                                              82066
44                                             282230
45                                              91038
46                                             653869
47                                            1995292
48                                               2143
49                                             258697
50                                               8619
51                                             323915
52                                             221695
53                                              77239
54                                             506890
55                                              43704
56  Most recent edit: 21:14, Thursday, January 14,...
57  ^ Nationality and location of original infecti...

                                                       \
                                               Deaths
                                           350,816[v]
0                                                4878
1                                                 214
2                                                   0
3                                               10141
4                                                3749
5                                               30513
6                                           4,873[vi]
7                                                5995
8                                                 921
9                                                 788
10                                              23585
11                                               9889
12                                                124
13                                                285
14                                               1436
15                                              17840
16                                               8613
17                                               3898
18                                               2879
19                                               2623
20                                               7488
21                                                438
22                                               5799
23                                              12423
24                                              14145
25                                               5711
26                                               4816
27                                               5540
28                                                961
29                                               1587
30                                               3019
31                                                735
32                                              19932
33                                               2403
34                                       32,007[viii]
35                                               7578
36                                               1152
37                                                  2
38                                               9802
39                                               2064
40                                               1138
41                                              18429
42                                               1272
43                                               1509
44                                               4739
45                                               1259
46                                               7785
47                                              30219
48                                                 24
49                                               1055
50                                                155
51                                               4411
52                                               2879
53                                                968
54                                               5157
55                                                405
56  Most recent edit: 21:14, Thursday, January 14,...
57  ^ Nationality and location of original infecti...

                                                       \
                                          Recov.[iii]
                                                    –
0                                              202137
1                                                7165
2                                                   –
3                                                   –
4                                              205462
5                                                   –
6                                                   –
7                                                   –
8                                               18371
9                                               17745
10                                                  –
11                                                  –
12                                               6660
13                                              11385
14                                              46247
15                                                  –
16                                             367800
17                                             188922
18                                                  –
19                                              36740
20                                             217930
21                                              10491
22                                                  –
23                                             187221
24                                             415079
25                                             417005
26                                             136627
27                                                  –
28                                              62778
29                                              80829
30                                                  –
31                                              23046
32                                                  –
33                                              43091
34                                             111141
35                                             521475
36                                              82935
37                                                 29
38                                             648724
39                                             200512
40                                                  –
41                                             556042
42                                                  –
43                                                  –
44                                                  –
45                                              77032
46                                             565197
47                                      1,595,600[ix]
48                                               1984
49                                             176211
50                                               5657
51                                                  –
52                                                  –
53                                              42462
54                                             472862
55                                              35281
56  Most recent edit: 21:14, Thursday, January 14,...
57  ^ Nationality and location of original infecti...

                                                       \
                                            Hosp.[iv]
                                                    –
0                                               34373
1                                                1013
2                                                   –
3                                               43582
4                                               11514
5                                                   –
6                                               16092
7                                               12257
8                                                   –
9                                                   –

## 1) Replace Headers

In [13]:
# Change the column names 
scraped_df.columns= ['A','State','Cases','Deaths','Recovered' , 'Hospitalized' , 'Ref', '7_levele_1','8_levele_1','9_levele_1']

In [14]:
# Print newly created datafram with updated headers
scraped_df

,A,State,Cases,Deaths,Recovered,Hospitalized,Ref,7_levele_1,8_levele_1,9_levele_1
0,NaN,Alabama,374095,4878,202137,34373,[35],NaN,NaN,NaN
1,NaN,Alaska,46552,214,7165,1013,[36],NaN,NaN,NaN
2,NaN,American Samoa,3,0,–,–,[37],NaN,NaN,NaN
3,NaN,Arizona,618546,10141,–,43582,[38],NaN,NaN,NaN
4,NaN,Arkansas,233475,3749,205462,11514,[39],NaN,NaN,NaN
5,NaN,California,2747288,30513,–,–,[40],NaN,NaN,NaN
6,NaN,Colorado,337161,"4,873[vi]",–,16092,[41],NaN,NaN,NaN
7,NaN,Connecticut,185708,5995,–,12257,[42][43],NaN,NaN,NaN
8,NaN,Delaware,56596,921,18371,–,[44],NaN,NaN,NaN
9,NaN,District of Columbia,29252,788,17745,–,[45],NaN,NaN,NaN
10,NaN,Florida[vii],1503482,23585,–,66204,[46],NaN,NaN,NaN
11,NaN,Georgia,575395,9889,–,40648,[47],NaN,NaN,NaN
12,NaN,Guam,7399,124,6660,–,[48],NaN,NaN,NaN
13,NaN,Hawaii,25470,285,11385,1159,[49],NaN,NaN,NaN
14,NaN,Idaho,141077,1436,46247,4746,[50][51],NaN,NaN,NaN
15,NaN,Illinois,1046030,17840,–,–,[52],NaN,NaN,NaN
16,NaN,Indiana,563653,8613,367800,37125,[53][54],NaN,NaN,NaN
17,NaN,Iowa,282439,3898,188922,–,[55],NaN,NaN,NaN
18,NaN,Kansas,229079,2879,–,5800,[56],NaN,NaN,NaN
19,NaN,Kentucky,265262,2623,36740,10736,[57][58],NaN,NaN,NaN
20,NaN,Louisiana,315275,7488,217930,–,[59],NaN,NaN,NaN
21,NaN,Maine,29611,438,10491,1171,[60],NaN,NaN,NaN
22,NaN,Maryland,283171,5799,–,23393,[61],NaN,NaN,NaN
23,NaN,Massachusetts,375178,12423,187221,14823,[62][63],NaN,NaN,NaN
24,NaN,Michigan,562553,14145,415079,–,[64],NaN,NaN,NaN
25,NaN,Minnesota,437552,5711,417005,22815,[65],NaN,NaN,NaN
26,NaN,Mississippi,218386,4816,136627,7703,[66],NaN,NaN,NaN
27,NaN,Missouri,397299,5540,–,–,[67],NaN,NaN,NaN
28,NaN,Montana,81555,961,62778,3080,[68],NaN,NaN,NaN
29,NaN,Nebraska,162849,1587,80829,4784,[69],NaN,NaN,NaN
30,NaN,Nevada,220124,3019,–,–,[70],NaN,NaN,NaN
31,NaN,New Hampshire,42697,735,23046,857,[71],NaN,NaN,NaN
32,NaN,New Jersey,590162,19932,–,53253,[72],NaN,NaN,NaN
33,NaN,New Mexico,139875,2403,43091,7832,[73],NaN,NaN,NaN
34,NaN,New York,1155370,"32,007[viii]",111141,89995,[74],NaN,NaN,NaN
35,NaN,North Carolina,629124,7578,521475,–,[75][76],NaN,NaN,NaN
36,NaN,North Dakota,90948,1152,82935,3059,[77],NaN,NaN,NaN
37,NaN,Northern Mariana Islands,122,2,29,4,[78],NaN,NaN,NaN
38,NaN,Ohio,792938,9802,648724,41863,[79],NaN,NaN,NaN
39,NaN,Oklahoma,269276,2064,200512,14328,[80],NaN,NaN,NaN
40,NaN,Oregon,105970,1138,–,5395,[81],NaN,NaN,NaN
41,NaN,Pennsylvania,741389,18429,556042,–,[82],NaN,NaN,NaN
42,NaN,Puerto Rico,109747,1272,–,–,[83],NaN,NaN,NaN
43,NaN,Rhode Island,82066,1509,–,5288,[84],NaN,NaN,NaN
44,NaN,South Carolina,282230,4739,–,–,[85],NaN,NaN,NaN
45,NaN,South Dakota,91038,1259,77032,5174,[86],NaN,NaN,NaN
46,NaN,Tennessee,653869,7785,565197,15307,[87],NaN,NaN,NaN
47,NaN,Texas,1995292,30219,"1,595,600[ix]",–,[88],NaN,NaN,NaN
48,NaN,US Virgin Islands,2143,24,1984,–,[89],NaN,NaN,NaN
49,NaN,Utah,258697,1055,176211,9421,[90],NaN,NaN,NaN
50,NaN,Vermont,8619,155,5657,–,[91],NaN,NaN,NaN
51,NaN,Virginia,323915,4411,–,28657,[92][93],NaN,NaN,NaN
52,NaN,Washington,221695,2879,–,12368,[94],NaN,NaN,NaN
53,NaN,West Virginia,77239,968,42462,–,[95],NaN,NaN,NaN
54,NaN,Wisconsin,506890,5157,472862,22378,[96],NaN,NaN,NaN
55,NaN,Wyoming,43704,405,35281,957,[97],NaN,NaN,NaN
56,"Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...",NaN
57,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,NaN

# 2)  Identify bad data and remove columns which has NaN

In [15]:
#Drop column A as it has all NaN values
clean_columns_df = scraped_df.dropna(axis=1)

In [16]:
# Print dataframe after deleting first column
clean_columns_df

,State,Cases,Deaths,Recovered,Hospitalized,Ref
0,Alabama,374095,4878,202137,34373,[35]
1,Alaska,46552,214,7165,1013,[36]
2,American Samoa,3,0,–,–,[37]
3,Arizona,618546,10141,–,43582,[38]
4,Arkansas,233475,3749,205462,11514,[39]
5,California,2747288,30513,–,–,[40]
6,Colorado,337161,"4,873[vi]",–,16092,[41]
7,Connecticut,185708,5995,–,12257,[42][43]
8,Delaware,56596,921,18371,–,[44]
9,District of Columbia,29252,788,17745,–,[45]
10,Florida[vii],1503482,23585,–,66204,[46]
11,Georgia,575395,9889,–,40648,[47]
12,Guam,7399,124,6660,–,[48]
13,Hawaii,25470,285,11385,1159,[49]
14,Idaho,141077,1436,46247,4746,[50][51]
15,Illinois,1046030,17840,–,–,[52]
16,Indiana,563653,8613,367800,37125,[53][54]
17,Iowa,282439,3898,188922,–,[55]
18,Kansas,229079,2879,–,5800,[56]
19,Kentucky,265262,2623,36740,10736,[57][58]
20,Louisiana,315275,7488,217930,–,[59]
21,Maine,29611,438,10491,1171,[60]
22,Maryland,283171,5799,–,23393,[61]
23,Massachusetts,375178,12423,187221,14823,[62][63]
24,Michigan,562553,14145,415079,–,[64]
25,Minnesota,437552,5711,417005,22815,[65]
26,Mississippi,218386,4816,136627,7703,[66]
27,Missouri,397299,5540,–,–,[67]
28,Montana,81555,961,62778,3080,[68]
29,Nebraska,162849,1587,80829,4784,[69]
30,Nevada,220124,3019,–,–,[70]
31,New Hampshire,42697,735,23046,857,[71]
32,New Jersey,590162,19932,–,53253,[72]
33,New Mexico,139875,2403,43091,7832,[73]
34,New York,1155370,"32,007[viii]",111141,89995,[74]
35,North Carolina,629124,7578,521475,–,[75][76]
36,North Dakota,90948,1152,82935,3059,[77]
37,Northern Mariana Islands,122,2,29,4,[78]
38,Ohio,792938,9802,648724,41863,[79]
39,Oklahoma,269276,2064,200512,14328,[80]
40,Oregon,105970,1138,–,5395,[81]
41,Pennsylvania,741389,18429,556042,–,[82]
42,Puerto Rico,109747,1272,–,–,[83]
43,Rhode Island,82066,1509,–,5288,[84]
44,South Carolina,282230,4739,–,–,[85]
45,South Dakota,91038,1259,77032,5174,[86]
46,Tennessee,653869,7785,565197,15307,[87]
47,Texas,1995292,30219,"1,595,600[ix]",–,[88]
48,US Virgin Islands,2143,24,1984,–,[89]
49,Utah,258697,1055,176211,9421,[90]
50,Vermont,8619,155,5657,–,[91]
51,Virginia,323915,4411,–,28657,[92][93]
52,Washington,221695,2879,–,12368,[94]
53,West Virginia,77239,968,42462,–,[95]
54,Wisconsin,506890,5157,472862,22378,[96]
55,Wyoming,43704,405,35281,957,[97]
56,"Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,..."
57,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...

# 3) Add a date column to the dataframe

In [17]:
# Add data field in dataframe
clean_columns_df["Updated_date"] = pd.date_range(start='1/13/2021' , end='1/13/2021', periods=len(clean_columns_df))

<ipython-input-17-576fb47803f7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_columns_df["Updated_date"] = pd.date_range(start='1/13/2021' , end='1/13/2021', periods=len(clean_columns_df))

In [18]:
# Print update dataframe 
clean_columns_df

,State,Cases,Deaths,Recovered,Hospitalized,Ref,Updated_date
0,Alabama,374095,4878,202137,34373,[35],2021-01-13
1,Alaska,46552,214,7165,1013,[36],2021-01-13
2,American Samoa,3,0,–,–,[37],2021-01-13
3,Arizona,618546,10141,–,43582,[38],2021-01-13
4,Arkansas,233475,3749,205462,11514,[39],2021-01-13
5,California,2747288,30513,–,–,[40],2021-01-13
6,Colorado,337161,"4,873[vi]",–,16092,[41],2021-01-13
7,Connecticut,185708,5995,–,12257,[42][43],2021-01-13
8,Delaware,56596,921,18371,–,[44],2021-01-13
9,District of Columbia,29252,788,17745,–,[45],2021-01-13
10,Florida[vii],1503482,23585,–,66204,[46],2021-01-13
11,Georgia,575395,9889,–,40648,[47],2021-01-13
12,Guam,7399,124,6660,–,[48],2021-01-13
13,Hawaii,25470,285,11385,1159,[49],2021-01-13
14,Idaho,141077,1436,46247,4746,[50][51],2021-01-13
15,Illinois,1046030,17840,–,–,[52],2021-01-13
16,Indiana,563653,8613,367800,37125,[53][54],2021-01-13
17,Iowa,282439,3898,188922,–,[55],2021-01-13
18,Kansas,229079,2879,–,5800,[56],2021-01-13
19,Kentucky,265262,2623,36740,10736,[57][58],2021-01-13
20,Louisiana,315275,7488,217930,–,[59],2021-01-13
21,Maine,29611,438,10491,1171,[60],2021-01-13
22,Maryland,283171,5799,–,23393,[61],2021-01-13
23,Massachusetts,375178,12423,187221,14823,[62][63],2021-01-13
24,Michigan,562553,14145,415079,–,[64],2021-01-13
25,Minnesota,437552,5711,417005,22815,[65],2021-01-13
26,Mississippi,218386,4816,136627,7703,[66],2021-01-13
27,Missouri,397299,5540,–,–,[67],2021-01-13
28,Montana,81555,961,62778,3080,[68],2021-01-13
29,Nebraska,162849,1587,80829,4784,[69],2021-01-13
30,Nevada,220124,3019,–,–,[70],2021-01-13
31,New Hampshire,42697,735,23046,857,[71],2021-01-13
32,New Jersey,590162,19932,–,53253,[72],2021-01-13
33,New Mexico,139875,2403,43091,7832,[73],2021-01-13
34,New York,1155370,"32,007[viii]",111141,89995,[74],2021-01-13
35,North Carolina,629124,7578,521475,–,[75][76],2021-01-13
36,North Dakota,90948,1152,82935,3059,[77],2021-01-13
37,Northern Mariana Islands,122,2,29,4,[78],2021-01-13
38,Ohio,792938,9802,648724,41863,[79],2021-01-13
39,Oklahoma,269276,2064,200512,14328,[80],2021-01-13
40,Oregon,105970,1138,–,5395,[81],2021-01-13
41,Pennsylvania,741389,18429,556042,–,[82],2021-01-13
42,Puerto Rico,109747,1272,–,–,[83],2021-01-13
43,Rhode Island,82066,1509,–,5288,[84],2021-01-13
44,South Carolina,282230,4739,–,–,[85],2021-01-13
45,South Dakota,91038,1259,77032,5174,[86],2021-01-13
46,Tennessee,653869,7785,565197,15307,[87],2021-01-13
47,Texas,1995292,30219,"1,595,600[ix]",–,[88],2021-01-13
48,US Virgin Islands,2143,24,1984,–,[89],2021-01-13
49,Utah,258697,1055,176211,9421,[90],2021-01-13
50,Vermont,8619,155,5657,–,[91],2021-01-13
51,Virginia,323915,4411,–,28657,[92][93],2021-01-13
52,Washington,221695,2879,–,12368,[94],2021-01-13
53,West Virginia,77239,968,42462,–,[95],2021-01-13
54,Wisconsin,506890,5157,472862,22378,[96],2021-01-13
55,Wyoming,43704,405,35281,957,[97],2021-01-13
56,"Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...","Most recent edit: 21:14, Thursday, January 14,...",2021-01-13
57,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,^ Nationality and location of original infecti...,2021-01-13

# 4) Delete row 56 and 57 as that information is not usefull

In [24]:
# Clena the footer rows from dataframe 
clean_columns_df = clean_columns_df[0:56 : ]

In [25]:
# Print update dataframe 
clean_columns_df

,State,Cases,Deaths,Recovered,Hospitalized,Ref,Updated_date
0,Alabama,374095,4878,202137,34373,[35],2021-01-13
1,Alaska,46552,214,7165,1013,[36],2021-01-13
2,American Samoa,3,0,–,–,[37],2021-01-13
3,Arizona,618546,10141,–,43582,[38],2021-01-13
4,Arkansas,233475,3749,205462,11514,[39],2021-01-13
5,California,2747288,30513,–,–,[40],2021-01-13
6,Colorado,337161,"4,873[vi]",–,16092,[41],2021-01-13
7,Connecticut,185708,5995,–,12257,[42][43],2021-01-13
8,Delaware,56596,921,18371,–,[44],2021-01-13
9,District of Columbia,29252,788,17745,–,[45],2021-01-13
10,Florida[vii],1503482,23585,–,66204,[46],2021-01-13
11,Georgia,575395,9889,–,40648,[47],2021-01-13
12,Guam,7399,124,6660,–,[48],2021-01-13
13,Hawaii,25470,285,11385,1159,[49],2021-01-13
14,Idaho,141077,1436,46247,4746,[50][51],2021-01-13
15,Illinois,1046030,17840,–,–,[52],2021-01-13
16,Indiana,563653,8613,367800,37125,[53][54],2021-01-13
17,Iowa,282439,3898,188922,–,[55],2021-01-13
18,Kansas,229079,2879,–,5800,[56],2021-01-13
19,Kentucky,265262,2623,36740,10736,[57][58],2021-01-13
20,Louisiana,315275,7488,217930,–,[59],2021-01-13
21,Maine,29611,438,10491,1171,[60],2021-01-13
22,Maryland,283171,5799,–,23393,[61],2021-01-13
23,Massachusetts,375178,12423,187221,14823,[62][63],2021-01-13
24,Michigan,562553,14145,415079,–,[64],2021-01-13
25,Minnesota,437552,5711,417005,22815,[65],2021-01-13
26,Mississippi,218386,4816,136627,7703,[66],2021-01-13
27,Missouri,397299,5540,–,–,[67],2021-01-13
28,Montana,81555,961,62778,3080,[68],2021-01-13
29,Nebraska,162849,1587,80829,4784,[69],2021-01-13
30,Nevada,220124,3019,–,–,[70],2021-01-13
31,New Hampshire,42697,735,23046,857,[71],2021-01-13
32,New Jersey,590162,19932,–,53253,[72],2021-01-13
33,New Mexico,139875,2403,43091,7832,[73],2021-01-13
34,New York,1155370,"32,007[viii]",111141,89995,[74],2021-01-13
35,North Carolina,629124,7578,521475,–,[75][76],2021-01-13
36,North Dakota,90948,1152,82935,3059,[77],2021-01-13
37,Northern Mariana Islands,122,2,29,4,[78],2021-01-13
38,Ohio,792938,9802,648724,41863,[79],2021-01-13
39,Oklahoma,269276,2064,200512,14328,[80],2021-01-13
40,Oregon,105970,1138,–,5395,[81],2021-01-13
41,Pennsylvania,741389,18429,556042,–,[82],2021-01-13
42,Puerto Rico,109747,1272,–,–,[83],2021-01-13
43,Rhode Island,82066,1509,–,5288,[84],2021-01-13
44,South Carolina,282230,4739,–,–,[85],2021-01-13
45,South Dakota,91038,1259,77032,5174,[86],2021-01-13
46,Tennessee,653869,7785,565197,15307,[87],2021-01-13
47,Texas,1995292,30219,"1,595,600[ix]",–,[88],2021-01-13
48,US Virgin Islands,2143,24,1984,–,[89],2021-01-13
49,Utah,258697,1055,176211,9421,[90],2021-01-13
50,Vermont,8619,155,5657,–,[91],2021-01-13
51,Virginia,323915,4411,–,28657,[92][93],2021-01-13
52,Washington,221695,2879,–,12368,[94],2021-01-13
53,West Virginia,77239,968,42462,–,[95],2021-01-13
54,Wisconsin,506890,5157,472862,22378,[96],2021-01-13
55,Wyoming,43704,405,35281,957,[97],2021-01-13

# 5) Delete column Ref

In [27]:
# Delete reference column 
del clean_columns_df['Ref']

In [28]:
clean_columns_df

,State,Cases,Deaths,Recovered,Hospitalized,Updated_date
0,Alabama,374095,4878,202137,34373,2021-01-13
1,Alaska,46552,214,7165,1013,2021-01-13
2,American Samoa,3,0,–,–,2021-01-13
3,Arizona,618546,10141,–,43582,2021-01-13
4,Arkansas,233475,3749,205462,11514,2021-01-13
5,California,2747288,30513,–,–,2021-01-13
6,Colorado,337161,"4,873[vi]",–,16092,2021-01-13
7,Connecticut,185708,5995,–,12257,2021-01-13
8,Delaware,56596,921,18371,–,2021-01-13
9,District of Columbia,29252,788,17745,–,2021-01-13
10,Florida[vii],1503482,23585,–,66204,2021-01-13
11,Georgia,575395,9889,–,40648,2021-01-13
12,Guam,7399,124,6660,–,2021-01-13
13,Hawaii,25470,285,11385,1159,2021-01-13
14,Idaho,141077,1436,46247,4746,2021-01-13
15,Illinois,1046030,17840,–,–,2021-01-13
16,Indiana,563653,8613,367800,37125,2021-01-13
17,Iowa,282439,3898,188922,–,2021-01-13
18,Kansas,229079,2879,–,5800,2021-01-13
19,Kentucky,265262,2623,36740,10736,2021-01-13
20,Louisiana,315275,7488,217930,–,2021-01-13
21,Maine,29611,438,10491,1171,2021-01-13
22,Maryland,283171,5799,–,23393,2021-01-13
23,Massachusetts,375178,12423,187221,14823,2021-01-13
24,Michigan,562553,14145,415079,–,2021-01-13
25,Minnesota,437552,5711,417005,22815,2021-01-13
26,Mississippi,218386,4816,136627,7703,2021-01-13
27,Missouri,397299,5540,–,–,2021-01-13
28,Montana,81555,961,62778,3080,2021-01-13
29,Nebraska,162849,1587,80829,4784,2021-01-13
30,Nevada,220124,3019,–,–,2021-01-13
31,New Hampshire,42697,735,23046,857,2021-01-13
32,New Jersey,590162,19932,–,53253,2021-01-13
33,New Mexico,139875,2403,43091,7832,2021-01-13
34,New York,1155370,"32,007[viii]",111141,89995,2021-01-13
35,North Carolina,629124,7578,521475,–,2021-01-13
36,North Dakota,90948,1152,82935,3059,2021-01-13
37,Northern Mariana Islands,122,2,29,4,2021-01-13
38,Ohio,792938,9802,648724,41863,2021-01-13
39,Oklahoma,269276,2064,200512,14328,2021-01-13
40,Oregon,105970,1138,–,5395,2021-01-13
41,Pennsylvania,741389,18429,556042,–,2021-01-13
42,Puerto Rico,109747,1272,–,–,2021-01-13
43,Rhode Island,82066,1509,–,5288,2021-01-13
44,South Carolina,282230,4739,–,–,2021-01-13
45,South Dakota,91038,1259,77032,5174,2021-01-13
46,Tennessee,653869,7785,565197,15307,2021-01-13
47,Texas,1995292,30219,"1,595,600[ix]",–,2021-01-13
48,US Virgin Islands,2143,24,1984,–,2021-01-13
49,Utah,258697,1055,176211,9421,2021-01-13
50,Vermont,8619,155,5657,–,2021-01-13
51,Virginia,323915,4411,–,28657,2021-01-13
52,Washington,221695,2879,–,12368,2021-01-13
53,West Virginia,77239,968,42462,–,2021-01-13
54,Wisconsin,506890,5157,472862,22378,2021-01-13
55,Wyoming,43704,405,35281,957,2021-01-13

In [29]:
# Print shape of update dataframe 
clean_columns_df.shape

(56, 6)

# 6) Find duplicates

In [33]:
# Check duplicates 
dedubbed_df = clean_columns_df.duplicated()
dedubbed_df.shape

(58,)

In [34]:
# The number of rows are same so there are no dubplicates in data frame

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
dtype: bool

In [1]:
# After seeing the resultes there are not dublicates
# Add a column with short state names